// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asysitgjfyownyzbfsno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzeXNpdGdqZnlvd255emJmc25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NjA0MzUsImV4cCI6MjA2NDEzNjQzNX0.-30jCcNZBwAN3Vai_Bs_5KMw1Td3mukv1uB-wP8RRO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);